name: Setup
description: Checkout, install, and build
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: Fetch tags
    #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        # TODO
        # check-latest: true
        cache: yarn

    - name: Install
      run: yarn install --frozen-lockfile --prefer-offline --check-files

    - name: Build
      run: yarn build
