name: Build, test, and release

permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [main, next]

env:
  ENVIRONMENT: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs: [build, lint, test]
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Configure NPM Access Token
        run: yarn config set 'npmAuthToken' "${{ secrets.NPM_TOKEN }}"

      - name: Ensure Valid Versioning
        run: yarn version check

      - run: git config user.email github-actions@github.com
      - run: git config user.name github-actions

      # - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      # - run: git config --local user.name "github-actions[bot]"

      - name: Release
        run: yarn workspaces foreach --verbose --no-private --topological-dev run release
