name: Build, test, and deploy

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: "Version Increment"
        required: true
        default: "warning"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
  pull_request:
    types: [closed]
    branches: [main, next]

env:
  ENVIRONMENT: build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: yarn test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        run: echo Publish

      # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # - run: ./scripts/publish-native.js $GITHUB_REF
      # - run: ./scripts/publish-release.sh

      # - uses: actions/cache@v3
      #   if: ${{needs.build.outputs.docsChange != 'docs only change'}}
      #   id: restore-build
      #   with:
      #     path: ./*
      #     key: ${{ github.sha }}-${{ github.run_number }}
