name: Build, test, and deploy

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: "Version Increment"
        required: true
        default: "warning"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
  pull_request:
    types: [closed]
    branches: [main, next]

env:
  ENVIRONMENT: build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Fetch tags
      #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline --check-files

  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test
        run: yarn test
      # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # - run: ./scripts/publish-native.js $GITHUB_REF
      # - run: ./scripts/publish-release.sh

      # - uses: actions/cache@v3
      #   if: ${{needs.build.outputs.docsChange != 'docs only change'}}
      #   id: restore-build
      #   with:
      #     path: ./*
      #     key: ${{ github.sha }}-${{ github.run_number }}
