name: Build, test, and deploy

on:
  workflow_dispatch:
    # inputs:
    #   versionIncrement:
    #     description: "Version Increment"
    #     required: true
    #     default: "warning"
    #     type: choice
    #     options:
    #       - major
    #       - minor
    #       - patch
    #       - premajor
    #       - preminor
    #       - prepatch
    #       - prerelease

  pull_request:
    types: [closed]
    branches: [main, next]

env:
  ENVIRONMENT: build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - uses: actions/cache@v3
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: yarn test

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps:
      - uses: actions/cache@v3
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Publish
        run: echo Publish

      - name: Configure NPM Access Token
        run: yarn config set 'npmRegistries["//npm.example.com"].npmAuthToken' "${{ secrets.NPM_TOKEN }}"

      - name: Ensure Valid Versioning
        run: yarn version check

      - name: Publish
        run: yarn workspaces foreach --verbose --no-private --topological-dev run release && git push --tags
