name: Build, test, and deploy

on:
  workflow_dispatch:
    inputs:
      versionIncrement:
        description: "Version Increment"
        required: true
        default: "warning"
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
  pull_request:
    types: [closed]
    branches: [main, next]

jobs:
  build_test_deploy:
    name: Build, test, and deploy
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: build
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Fetch tags
      #   run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install
        run: yarn install --frozen-lockfile --check-files
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # - run: ./scripts/publish-native.js $GITHUB_REF
      # - run: ./scripts/publish-release.sh

      # - uses: actions/cache@v3
      #   if: ${{needs.build.outputs.docsChange != 'docs only change'}}
      #   id: restore-build
      #   with:
      #     path: ./*
      #     key: ${{ github.sha }}-${{ github.run_number }}
