name: Release

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        options: [staging, production]
        description: Environment
        required: true
        default: staging
      title:
        type: string
        description: Title
        required: true
      message:
        type: string
        description: Message
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Branch Protection
        run: |-
          if ${{ inputs.env == 'production' && github.ref_name != 'main' }}; then
            exit 1
          fi

      - name: Tag and push
        run: |-
          STAGING=${{ inputs.env == 'staging' && 'staging/' || '' }}
          DATE=$(date +%Y.%b.%d | cut -b 3- | tr '[:upper:]' '[:lower:]')
          SLUG=$(echo "${{ inputs.title }}" | iconv -t ascii//TRANSLIT | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
          TAG=release/$STAGING$DATE/$SLUG

          echo STAGING $STAGING
          echo DATE $DATE
          echo SLUG $SLUG
          echo TAG $TAG

          git tag -a "$TAG" -m '${{ inputs.message }}'
          git push --tags
